# simcore_ai/types/identity/exceptions.py
from __future__ import annotations

from simcore_ai.exceptions.base import SimCoreError


class IdentityError(SimCoreError): ...
