# simcore_ai/client/exceptions.py
from __future__ import annotations

from simcore_ai.exceptions.base import SimCoreError

pass
